name: 'Build and Test'
description: 'Build and test an VSCode extension'
inputs:
  working-directory:
    description: 'The working directory to run commands in'
    required: true
    default: '.'
runs:
  using: 'composite'
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npm install

    - name: Run tests (Linux)
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: xvfb-run -a npm test
      if: runner.os == 'Linux'

    - name: Run tests (Non-Linux)
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npm test
      if: runner.os != 'Linux'
