name: 'Build and Test'
description: 'Build and test an VSCode extension'
inputs:
  working-directory:
    description: 'The working directory to run commands in'
    required: true

runs:
  using: 'composite'
  working-directory: ${{ inputs.working-directory }}
  shell: bash
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - run: echo ${{ inputs.working-directory }}

    # run npm ci preventing script access to npm auth token
    - name: Install dependencies
      run: npm ci --ignore-scripts

    - run: npm run audit

    - run: npm run lint

    - name: Run tests (Linux)
      run: xvfb-run -a npm test
      if: runner.os == 'Linux'

    - name: Run tests (Non-Linux)
      run: npm test
      if: runner.os != 'Linux'
