name: 'Build and Test'
description: 'Build and test the extensions'

runs:
  using: 'composite'
  steps:
    # run npm ci preventing script access to npm auth token
    - name: Install dependencies
      run: npm ci --ignore-scripts
      shell: bash

    - run: npm run lint
      shell: bash

    - run: npm run audit
      shell: bash

    # The workspace used in the python tests requires Python and Poetry
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Set up Poetry
      run: |
        pip install --user pipx
        pipx ensurepath
        pipx install poetry ${{ runner.os == 'macOS' && '--python "$Python_ROOT_DIR/bin/python"' || '' }}
        pipx inject poetry poetry-plugin-export
      shell: bash

    - name: Run tests (Linux)
      run: xvfb-run -a npm test
      if: runner.os == 'Linux'
      shell: bash

    - name: Run tests (Non-Linux)
      run: npm test
      if: runner.os != 'Linux'
      shell: bash

    # Tests need to be run before build, as tests build to the same location
    - run: npm run build
      shell: bash
