on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # run npm ci preventing script access to npm auth token
      - run: npm ci --ignore-scripts
        shell: bash

      - run: npm run audit

      - name: Build and Test
        uses: ./.github/actions/build-and-test
        with:
          working-directory: './extensions/algorand-python'
