on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      # run npm ci preventing script access to npm auth token
      - run: npm ci --ignore-scripts

      - run: npm run audit

      - name: Build and Test (Algorand Python)
        uses: ./.github/actions/build-and-test
        with:
          working-directory: './extensions/algorand-python'

  create-release:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Create GitHub release
        uses: ./.github/actions/create-release
        id: create-github-release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
