name: Pull Request

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 8 * * 1' # Each monday 8 AM UTC

permissions:
  contents: write
  issues: read

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: ./package-lock.json

      - name: Build and Test
        uses: ./.github/actions/build-and-test

      - run: ls -la
      - run: ls ./packages/python/dist
      - run: ls ./packages/typescript/dist

      - name: Upload python build output
        uses: actions/upload-artifact@v4
        with:
          name: python-dist
          path: 'packages/python/dist'
          if-no-files-found: error

      - name: Upload typescript build output
        uses: actions/upload-artifact@v4
        with:
          name: typescript-dist
          path: 'packages/typescript/dist'
          if-no-files-found: error
